---
title: "FS Analysis"
output: html_notebook
---
# Author: Vince Fasanello
# Date: June 2021
# Project: Fluctuating selection project, Analyses & Outputs for Manuscript.


# File Description:-------------------------------------------------------------
#   
#   |-----------------------------------------------------------------------|
#   | This script, run in it's entirety, executes all analyses and produces |
#   | All figure and table outputs used in the manuscript.                  |
#   |-----------------------------------------------------------------------|
# 
# Inputs-&-Outputs: -------------------
# 	Inputs:
# 		[1] "metadatapluscounts.rdata" : A ".Rdata" type file containing the combined data from the 
#                                      counts.expected dataframes form library 1 and library 2 and
#                                      appended metadata information. -produced in Fitness_Assays step 2-
#
# 		[2] "swref.rdata" : A ".Rdata" type file containing data for single-well reference samples from the fit assays
#                         used to assess barcode contamination during evolution. -produced in Fitness_Assays step 2-
#
# 		[3] "swref.rdata" : A ".Rdata" type file containing data for single-well reference samples from the evolutionary dynamics
#                         data used to assess barcode contamination during evolution. -produced in Evoutionary_Dynamics step 2-
#
# 		[4] "FitAssayData.rdata" : A set of ".Rdata" type files containing formatted 
#                                dataframes for analysis. -produced in Fitness_Assays step 2-
# 			
# 	Outputs:
#     Figures and tables for Manuscript...
# 		    [1]  000_Figure_1.pdf
#         [2]  000_Figure_1.png
#         [3]  000_Figure_2.pdf
#         [4]  000_Figure_2.png
#         [5]  000_Figure_3.pdf
#         [6]  000_Figure_3.png
#         [7]  000_Figure_4.pdf
#         [8]  000_Figure_4.png
#         [9]  000_Figure_S1.pdf
#         [10] 000_Figure_S1.png
#         [11] 000_Figure_S2.pdf
#         [12] 000_Figure_S2.png
#         [13] 000_Figure_S3.pdf
#         [14] 000_Figure_S3.png
#         [15] 000_Table_S3.csv
#         [16] 000_Table_S4.csv
#         [17] 000_Table_S6.html
#         [18] 000_Table_S7.html
#         ***Note: there are additional outputs that can be turned on throughout
#                  the script if desired.
# ------------------------------------------------------------------------------ 		    


  
```{R Setup, warning = FALSE}
# Environment & Notebook Setup -------------------------------------------------
rm(list = ls())
options(scipen = 999)
knitr::opts_chunk$set(tidy = TRUE, collapse = TRUE)


# Set Working Directory Paths --------------------------------------------------
DIR_HOME <- # set this directory to the location of FS_Code_Supplement
DIR_HOME <- "C:/Users/VJF/Documents/GitHub/Fluctuating_Selection_Project/FS_Code_Supplement"
DIR_counts_in <- paste0(DIR_HOME,"/Fitness_Assays/2_CountstoAnalysis/Counts_Data/Combined")
DIR_evo_formatted <- paste0(DIR_HOME,"/Evolutionary_Dynamics/2_CountstoAnalysis/Formatted_Data")
DIR_fit_formatted <- paste0(DIR_HOME,"/Fitness_Assays/2_CountstoAnalysis/Formatted_Data")
DIR_out <- paste0(getwd(), "/Outputs")


# Load Packages ----------------------------------------------------------------
require(pwr)
require(ggplot2)
require(grid)
require(gridExtra)
require(cowplot)
require(lme4)
require(lmerTest)
require(ggthemes)
require(sjPlot)
require(weights)
require(dplyr)
require(car)
require(reshape2)


# Specify helper functions -----------------------------------------------------
# get_lower_tri ------------------------
#   Input: correlation or coefficient matrix (square)
#   Output: Lower triangle of input matrix (for plotting)
get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# --------------------------------------


# getline ------------------------------
#   Input: points, b & c
#   Output: Equation for a line that passes through points b & c
getline <- function(b,c){
  sl <- (b[2] - c[2])/(b[1] - c[1])
  interc = b[2] - sl*b[1]
  return(c(sl, interc))
}
# --------------------------------------


# dist2d -------------------------------
#   Input: Points a, b, c; a is target point, b & c define the line.
#   Output: orthagonal distance from a to b----c
dist2d <- function(a,b,c) {
 v1 <- b - c
 v2 <- a - b
 m <- cbind(v1,v2)
 d <- abs(det(m))/sqrt(sum(v1*v1))
 return(d)
}
# --------------------------------------


# lineside -----------------------------
#   Input: points a, b, c; a is target point, b & c define the line.
#   Ouptut: sign; + = above and to the right; - = below and to the left. 
lineside <- function(a,b,c) {
  sign((c[1] - b[1])*(a[2] - b[2]) - (c[2] - b[2])*(a[1] - b[1]))*-1
}
# --------------------------------------



# get_legend ---------------------------
#   Input: ggplot with legend
#   Output: The legend only (for inserting in other plots with difficult to handle legends)
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
# --------------------------------------


# %ni% ---------------------------------
#   Negates the %in% operator.
'%ni%' <- Negate('%in%')
# --------------------------------------


# Specify Palette for plotting ---------
mypalette <- RColorBrewer::brewer.pal(n = 11, name = "BrBG")[c(11,10,9,8,3,2,1)]
# --------------------------------------


# define a custom theme for plots ------
theme_VJF <- function(){
  theme_classic()+
  theme(
    # adjust axis title, text, ticks ---
    axis.title = element_text(size = 10, face = "bold", color = "black"),
    axis.text = element_text(size = 8, face = "bold", color = "black"),
    axis.ticks = element_line(color = "black"),
    
    # adjust legend viz ----------------
    legend.background = element_rect(colour = 'black', fill = 'grey95', size = 1, linetype='solid'),
    legend.key.size = unit(10,"pt"),
    
    # adjust plot label format ---------
    plot.tag = element_text(size = 20, face = "bold", color = "black")
  )
}
# --------------------------------------
```
<br/><br/>


```{R Counts, warning = FALSE}
# obtain & prep counts data ----------------------------------------------------
setwd(DIR_counts_in); load("metadatapluscounts.rdata")
temp <- myd[myd$sample.type == "MPA_Plate", 125:237] # retain only fitness assay entries.
temp <- temp[,which(colnames(temp) %ni% c("d2C5", "d2C9"))] # omit two problem barcodes.
lowcut <- 20; temp[temp <= lowcut] <- NA # Data supported by <= 20 counts are noise.
reportvals <- paste0(sum(temp, na.rm = T), " total counts (reference included)")
temp <- temp[,which(colnames(temp) %ni% c("d1C2"))] # omit reference barcode.
reportvals <- c(reportvals, paste0(sum(temp, na.rm = T), " total counts (reference omitted)"))
temp2 <- colMeans(temp, na.rm = T) # barcode X sample --> barcode


# Visualization ----------------------------------------------------------------
countshist <- function(pdata, pxlab, pylab, ptag, plog = FALSE, plims = NA){
  # histogram with density overlay -----
  if(plog == TRUE){
    pZZ <- ggplot(data = data.frame(pdata[!is.na(pdata)]), aes(x = pdata[!is.na(pdata)])) + 
      geom_histogram(aes(y=..density..), colour="black", fill="gray90", bins = 50)+
      geom_density(alpha=.2, fill=NA)+
      scale_x_continuous(name = pxlab, limits = plims,expand = expansion(mult = c(0,0.02)))
  } else {
  # histogram with no density overlay --
    pZZ <- ggplot(data = data.frame(pdata[!is.na(pdata)])) + 
      geom_histogram(aes(x= pdata[!is.na(pdata)]), colour="black", fill="gray90", bins = 50) +
      scale_x_continuous(name = pxlab, expand = expansion(mult = c(0,0.02)))
  }
  # shared commands --------------------
  pZZ <- pZZ + 
    scale_y_continuous(name = "Frequency", expand = expansion(mult = c(0,0.02)))+
    theme_VJF() + labs(tag = ptag)
  return(pZZ)
}
pAA <- countshist(unlist(temp), "Counts", "Frequency", "A")
pBB <- countshist(log(unlist(temp)), "Log Counts", "Frequency", "B", TRUE, c(0,15))
pCC <- countshist(unlist(temp2), "Barcode Mean Counts", "Frequency", "C")
pDD <- countshist(log(unlist(temp2)), "Log Barcode Mean Counts", "Frequency", "D", TRUE, c(0,15))


# Save outputs to file ---------------------------------------------------------
setwd(DIR_out); pdf("000_Figure_S1.pdf", height = 7, width = 7)
cowplot::plot_grid(pAA,pBB,pCC,pDD, nrow=2, align = "v"); dev.off()

png("000_Figure_S1.png", width = 7, height = 7, units = "in", res = 300)
cowplot::plot_grid(pAA,pBB,pCC,pDD, nrow=2, align = "v"); dev.off()

# report -----------------------------------------------------------------------
for (i in 1:2){print(reportvals[i])}
print("Counts per barcode across 117 fitness assay sample pools"); summary(temp2)
rm(myd, temp, temp2, lowcut, pAA, pBB, pCC ,pDD, reportvals, DIR_counts_in, countshist, i) # tidy.
```
<br/><br/>


```{R Barcode Cross-Contamination, warning=FALSE}
# NOTE: replace ccpt with ccpm in all reportvals[n] lines to report mean contamination rather than total barcode cross-contamination (IF DESIRED)

# Reference purity. ------------------------------------------------------------
setwd(DIR_fit_formatted); load("swref.rdata")
temp <- swref[,c("ppects", "ppccts", "ppcctsm","cc", "ccm")]; rm(swref)
mycc <- as.data.frame(cbind(mean(temp$ppects), sd(temp$ppects), mean(temp$ppccts), sd(temp$ppccts), 
                            mean(temp$ppcctsm), sd(temp$ppcctsm), mean(temp$cc), sd(temp$cc),
                            mean(temp$ccm), sd(temp$ccm), length(temp$ppects)))
colnames(mycc) <- c("ec_mean", "ec_se", "uct_mean", "uct_se", "ucm_mean", "ucm_se",
                    "ccpt_mean", "ccpt_se", "ccpm_mean", "ccpm_se", "n_reps")
mycc$day <- NA; mycc$plateloc <- NA; mycc$group <- "ref"
reportvals <- rep(NA, times = 12)
reportvals[1] <- paste0("Mean Total Reference CC = ", round(mycc[1,]$ccpt_mean*100, 5), "%")
reportvals[2] <- paste0("SD Total Reference CC = ", round(mycc[1,]$ccpt_se*100, 5), "%")


# single well controls ---------------------------------------------------------
setwd(DIR_evo_formatted); load("swref.rdata")
temp <- swref[,c("ppects", "ppccts", "ppcctsm","cc", "ccm", "replicate")]; rm(swref)
temp <- temp[c(1:(nrow(temp) - 3)),] # remove sulf samples (not part of this project)
temp1s <- temp[c((nrow(temp) - 2):nrow(temp)),]; temp <- temp[c(1:(nrow(temp) - 3)),]
temp1s <- as.data.frame(cbind(temp1s$ppects, NA, temp1s$ppccts, NA, temp1s$ppcctsm, NA, temp1s$cc,
                              NA, temp1s$ccm, NA, 1, 50, c("A1", "E6", "F8"), "COPR"))
colnames(temp1s) <- colnames(mycc); mycc <- rbind(mycc, temp1s); rm(temp1s) 
days <- c(rep(0, times = 9), rep(50, times = 9))
platelocs <- rep(c("A1", "A1", "A1", "E6", "E6", "E6", "F8", "F8", "F8"), times = 2)
groups <- c(rep("ancestral", times = 9), rep("SALT", times = 9))
i <- 1
while (i <= (nrow(temp) - 2)) {
  tem <- temp[i:(i+2),]
  tem <- as.data.frame(cbind(mean(tem$ppects), sd(tem$ppects), mean(tem$ppccts), sd(tem$ppccts),
                             mean(tem$ppcctsm), sd(tem$ppcctsm), mean(tem$cc), sd(tem$cc), 
                             mean(tem$ccm), sd(tem$ccm), length(tem$ppects)))
  colnames(tem) <- c("ec_mean", "ec_se", "uct_mean", "uct_se", "ucm_mean", "ucm_se",
                     "ccpt_mean", "ccpt_se", "ccpm_mean", "ccpm_se", "n_reps")
  tem$day <- days[i]; tem$plateloc <- platelocs[i]; tem$group <- groups[i]
  mycc <- rbind(mycc, tem); rm(tem); i <- i + 3
}; rm(days, platelocs, groups, temp, i)
for(i in 1:(ncol(mycc) -2)){mycc[,i] <- as.numeric(mycc[,i])}; rm(i)
reportvals[3] <- paste0("Mean Total Ancestral (D0) CC = ", round(mean(mycc[mycc$group == "ancestral",]$ccpt_mean)*100, 5), "%")
reportvals[4] <- paste0("SD Total Ancestral (D0) CC = ", round(sd(mycc[mycc$group == "ancestral",]$ccpt_mean)*100, 5), "%")
reportvals[5] <- paste0("Mean Total ALL Evolved (D50) CC = ", round(mean(mycc[mycc$group %in% c("SALT","COPR"),]$ccpt_mean)*100, 5), "%")
reportvals[6] <- paste0("SD Total ALL Evolved (D50) CC = ", round(sd(mycc[mycc$group %in% c("SALT","COPR"),]$ccpt_mean)*100, 5), "%")
reportvals[7] <- paste0("Mean Total SALT Evolved (D50) CC = ", round(mean(mycc[mycc$group == "SALT",]$ccpt_mean)*100, 5), "%")
reportvals[8] <- paste0("SD Total SALT Evolved (D50) CC = ", round(sd(mycc[mycc$group == "SALT",]$ccpt_mean)*100, 5), "%")
reportvals[9] <- paste0("Mean Total COPR Evolved (D50) CC = ", round(mean(mycc[mycc$group == "COPR",]$ccpt_mean)*100, 5), "%")
reportvals[10] <- paste0("SD Total COPR Evolved (D50) CC = ", round(sd(mycc[mycc$group == "COPR",]$ccpt_mean)*100, 5), "%")
reportvals[11] <- paste0("Mean Total ALL CC = ", round(mean(mycc[mycc$group %in% c("SALT","COPR", "ancestral"),]$ccpt_mean)*100, 5), "%")
reportvals[12] <- paste0("SD Total ALL CC = ", round(sd(mycc[mycc$group %in% c("SALT","COPR", "ancestral"),]$ccpt_mean)*100, 5), "%")

# # Save outputs to file -------------------------------------------------------
# setwd(DIR_out); write.csv(mycc, file = "000_Table_cc.csv") # output table behind reported if desired.

# report -----------------------------------------------------------------------
for (i in 1:12){print(reportvals[i])}
rm(mycc, reportvals, i, DIR_evo_formatted) # tidy
```
<br/><br/>


```{R Power Analysis, warning = FALSE}
setwd(DIR_fit_formatted); load("FitAssayData.rdata") # load fitness assay data, we will use it from here forward.

# Calculate power to detect indiv BC fitness increase / decrease (t-tests) -----
# d=m1 - m2 / q; m1 is mean group 1, m2 is mean group 2, q is common standard deviation in the two groups
# here m1 is change in fitness and m2 is 0. mean q is used and is the weighted mean of all
# population standard deviation of the four replicate sets in each row of the dataset.
# ------------------------------------------------------------------------------
temp <- myrc[!is.na(myrc$fit_e_1) & !is.na(myrc$fit_e_2) & !is.na(myrc$fit_e_3) & !is.na(myrc$fit_e_4)
             & !is.na(myrc$fit_a) & !is.na(myrc$dw) & !is.na(myrc$reads_dw),]
temp$dw_1 <- temp$fit_e_1 - temp$fit_a; temp$psd_r1 <- ((temp$dw - temp$dw_1)^2)/4
temp$dw_2 <- temp$fit_e_2 - temp$fit_a; temp$psd_r2 <- ((temp$dw - temp$dw_2)^2)/4
temp$dw_3 <- temp$fit_e_3 - temp$fit_a; temp$psd_r3 <- ((temp$dw - temp$dw_3)^2)/4
temp$dw_4 <- temp$fit_e_4 - temp$fit_a; temp$psd_r4 <- ((temp$dw - temp$dw_4)^2)/4
temp$psd_m <- rowMeans(cbind(temp$psd_r1, temp$psd_r2, temp$psd_r3, temp$psd_r4), na.rm=T)
psd <- weighted.mean(sqrt(temp$psd_m), temp$reads_dw, na.rm=T); rm(temp)

powerBC <- matrix(nrow=100, ncol=5)
colnames(powerBC) <- c("fitchange", "psd", "n", "power", "sig.level")
powerBC <- as.data.frame(powerBC)
powerBC$fitchange <- seq(0,0.04,length.out=100) # fitness changes to calculate power for.
powerBC$psd <- psd # psd calculated above
powerBC$n <- 4 # n replicates
powerBC$sig.level <- 0.05 # significance level
for(i in 1:nrow(powerBC)){
  powerBC$power[i] <- pwr.t.test(d=powerBC$fitchange[i] / powerBC$psd[i],
                                 n=powerBC$n[i], sig.level=powerBC$sig.level[i])$power
}; rm(i) # calculate power
reportvals <- c(NA, NA, NA, NA, NA, NA)
reportvals[1] <- paste0(pwr.t.test(d=0.01 / psd, n=4, sig.level=0.05)$power*100, "% power to detect a 1% fitness change for an average BC")
reportvals[2] <- paste0("80% power to detect a ", pwr.t.test(power=0.8, n=4, sig.level=0.05)$d*psd*100, "% fitness change for an average BC")


# Calculate power to detect Treatment effects (lmer model) ---------------------
# f2 (effect size)=1/rmse (where rmse=root mean square error among replicate measures of dw). obtain rmse via 
# rmse=sqrt(mean(residuals(MODEL)^2))*100. Use pwr.f2.test in pwr package to obtain power to detect treatment 
# effects between treatments with a TOTAL number of barcodes equal to v+2=n between them. 
# ------------------------------------------------------------------------------
temp <- my[my$mpasp %in% c(0.0, 0.8), ] # Restrict to SALT & COPR dw data in 0.0 and 0.8 environments
temp$ID <- paste0(temp$bcpID, temp$mpasp) 
# rmse from the model*100 --> effect size of 1 corresonds to an x.xx% (rmse) fitness change.
myrmse <- sqrt(mean(residuals(lm(temp$dw ~ temp$ID + 0, weights=I(log(temp$re_dw))))^2))*100
# effect size of 1 is an x.xx% (rmse) fitness cahnge, so for a fitness change of 1(%), expect effect size of 1/x.xx (1/rmse)=x.xxx.
myeffectsize <- 1/myrmse; rm(temp) 

powerTR <- matrix(nrow=200, ncol=5)
colnames(powerTR) <- c("u", "v", "power", "f2", "sig.level")
powerTR <- as.data.frame(powerTR)
powerTR$v  <- c(rep((32*2) -1 -1, times=100), rep((16*2) -1 -1, times=100)) # v's
powerTR$u <- 1 # u
powerTR$n <- powerTR$v + 2; powerTR$n <- factor(powerTR$n, levels=c(64,32)) # n=v+2
powerTR$f2 <- seq(0, myeffectsize*1.5, length.out=100) # effect size
powerTR$sig.level <- 0.05 # significance level
for(i in 1:nrow(powerTR)){
  powerTR$power[i] <-  pwr.f2.test(u=powerTR$u[i], v=powerTR$v[i], f2=powerTR$f2[i],
                                   sig.level=powerTR$sig.level[i])$power
}; rm(i)
powerTR$f2 <- powerTR$f2*myrmse # scale effect size to be % fitness difference.
reportvals[3] <- paste0(pwr.f2.test(u=1, v=((32*2) -1 - 1), f2=myeffectsize, sig.level=0.05)$power*100, "% power to detect a 1% fitness change between treatments (Best Case)")
reportvals[4] <- paste0("80% power to detect a ", pwr.f2.test(u=1, v=((32*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, "% fitness change between treatments (Best Case)")
reportvals[5] <- paste0(pwr.f2.test(u=1, v=((16*2) -1 - 1), f2=myeffectsize, sig.level=0.05)$power*100, "% power to detect a 1% fitness difference between treatments (Worst Case)")
reportvals[6] <- paste0("80% power to detect a ", pwr.f2.test(u=1, v=((16*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, "% fitness change for an average BC (Worst Case)")


# Visualization ----------------------------------------------------------------
# panel A: individual barcode power ----
pAA<-ggplot(powerBC, aes(x=fitchange, y=power)) +
  geom_segment(x=pwr.t.test(power=0.8, n=4, sig.level=0.05)$d*psd,
               xend=pwr.t.test(power=0.8, n=4, sig.level=0.05)$d*psd, y=0, yend=0.8, lty="dotdash", color="gray", size=0.25)+
  geom_segment(x=0, xend=pwr.t.test(power=0.8, n=4, sig.level=0.05)$d*psd, y=0.8, yend=0.8, lty="dotdash", color="gray", size=0.25)+
  geom_point(x=pwr.t.test(power=0.8, n=4, sig.level=0.05)$d*psd, y=0.8, pch=19, size=3, color="darkgray")+
  geom_text(x=2.5/100, y=0.75, color="darkgray", size=2, label=paste0(round(pwr.t.test(power=0.8, n=4, sig.level=0.05)$d*psd*100,2), ", 80"))+
  geom_line()+
  scale_x_continuous(name="Fitness Change (%)\n (for Individual Strains) \n ", breaks=seq(0.0,0.04,by=0.005),
                     labels=seq(0.0,0.04,by=0.005)*100, limits=c(0,0.04), expand=expansion(mult=c(0,0.02)))+
  scale_y_continuous(name="Power (%)", breaks=seq(0.00,1.00,by=0.25), labels=seq(0.00,1.00,by=0.25)*100, limits=c(0,1), expand=expansion(mult=c(0,0.02)))+
  theme_VJF() + 
  labs(tag="A")
# --------------------------------------


# panel B: treatment power -------------
pBB<-ggplot(powerTR, aes(x=f2, y=power, group=n)) +
  geom_segment(x=pwr.f2.test(u=1, v=((32*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse,
               xend=pwr.f2.test(u=1, v=((32*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, y=0, yend=0.8, lty="dotdash", color="gray", size=0.25)+
  geom_segment(x=pwr.f2.test(u=1, v=((16*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse,
               xend=pwr.f2.test(u=1, v=((16*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, y=0, yend=0.8, lty="dotdash", color="gray", size=0.25)+
  geom_segment(x=0, xend=pwr.f2.test(u=1, v=((16*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, y=0.8, yend=0.8, lty="dotdash", color="gray", size=0.25)+
  geom_point(x=pwr.f2.test(u=1, v=((32*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, y=0.8, pch=19, size=3, color="darkgray")+
  geom_point(x=pwr.f2.test(u=1, v=((16*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, y=0.8, pch=19, size=3, color="darkgray")+
  geom_text(x=0.19, y=0.85, color="darkgray", size=2, label=paste0(round(pwr.f2.test(u=1, v=((32*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, 2),", 80"))+
  geom_text(x=0.75, y=0.75, color="darkgray", size=2, label=paste0(round(pwr.f2.test(u=1, v=((16*2) -1 - 1), power=0.8, sig.level=0.05)$f2*myrmse, 2),", 80"))+
  geom_line(aes(lty=n))+
  scale_x_continuous(name="Fitness Change (%)\n (for Treatments) \n ", breaks=seq(0.0,1.5,by=0.25),
                     labels=seq(0.0,1.5,by=0.25), limits=c(0,1.5), expand=expansion(mult=c(0,0.02)))+
  scale_y_continuous(name="Power (%)", breaks=seq(0.00,1.00,by=0.25), labels=seq(0.00,1.00,by=0.25)*100, limits=c(0,1), expand=expansion(mult=c(0,0.02)))+
  theme_VJF() + theme(legend.position=c(0.9,0.3)) + labs(tag="B")
# --------------------------------------


# Save outputs to file ---------------------------------------------------------
setwd(DIR_out); write.csv(powerBC, file="000_Table_S4.csv")

setwd(DIR_out); write.csv(powerTR, file="000_Table_S3.csv")

setwd(DIR_out); pdf(file="000_Figure_S2.pdf", width=3.345, height=6.69)
cowplot::plot_grid(pAA, pBB, nrow=2); dev.off()

png("000_Figure_S2.png", width=3.345, height=6.69, units = "in", res = 300)
cowplot::plot_grid(pAA, pBB, nrow=2); dev.off()

# # report -----------------------------------------------------------------------
for (i in 1:6){print(reportvals[i])}
rm(pAA, pBB, powerBC, powerTR, myeffectsize, myrmse, psd, i, reportvals) # tidy
```
<br/><br/>


```{R Single Environment Treatment Effects: Models, warning = FALSE}
# setup ------------------------------------------------------------------------
setwd(DIR_out)
chems <- list(c("SALT_A", "SALT_B"), c("COPR_A", "COPR_B"))
envs <- c(0.0, 0.8) # can add 0.4, 1.2 as well if desired. 

# among treatment effects X chemical X environment -----------------------------
#   Note: these data are used for plotting below
treatlist <- c("EH0","EH0_40","EH40","EH20_60","EH0_80","EH40_80","EH80")
treattreatlist <- paste0("treat", treatlist)
myres <- matrix(nrow=7, ncol=7)
rownames(myres) <- treattreatlist; colnames(myres) <- rownames(myres)
for (g in 1:length(chems)){
  for (h in 1:length(envs)){
    myres_p <- myres; myres_est <- myres
    for(i in 1:length(treatlist)){
      m <- my[my$mpasp==envs[h] & my$epo %in% chems[[g]] & !is.na(my$dw) & !is.na(my$re_dw),]
      m$treat <- relevel(m$treat, ref=treatlist[i])
      mod <- lmer(dw ~ treat + (1|bcpID), data=m)
      # print(tab_model(mod, digits=5, digits.p=8, show.stat=T, wrap.labels=100,
      #                 file=paste0("000_Table_treatVtreat_",strsplit(chems[[g]][1], "_")[[1]][1],"_",envs[h], ".html"))) # save individual models if desired
      for(j in 1:length(treattreatlist)){
        if(treatlist[j] !=treatlist[i]){
          myres_est[treattreatlist[i],treattreatlist[j]] <- summary(mod)$coefficients[treattreatlist[j], "Estimate"]
          myres_p[treattreatlist[i],treattreatlist[j]] <- summary(mod)$coefficients[treattreatlist[j], "Pr(>|t|)"]
        }
      }
    }
    colnames(myres_est) <-  treatlist; rownames(myres_est) <- treatlist
    colnames(myres_p) <- treatlist; rownames(myres_p) <- treatlist
    assign(paste0("myres_est_",strsplit(chems[[g]][1], "_")[[1]][1],"_",envs[h]), myres_est)
    assign(paste0("myres_p_",strsplit(chems[[g]][1], "_")[[1]][1],"_",envs[h]), myres_p)
    }
}; rm(m, mod, g, h, i, j, treatlist, treattreatlist, myres_est, myres_p, myres)


# treatment vs 0. X chemical X environment -------------------------------------
for (i in 1:length(chems)){
  for (j in 1:length(envs)){
      m <- my[my$mpasp==envs[j] & my$epo %in% chems[[i]] & !is.na(my$dw),]
      mod <- lmer(dw ~ treat + 0 + (1|bcpID), data=m)
      # print(tab_model(mod, digits=5, digits.p=8, show.stat=T, wrap.labels=100,
      #                 file=paste0("000_Table_treatV0",strsplit(chems[[i]][1], "_")[[1]][1],"_",envs[j], ".html")))  # save individual models if desired
  }
}; rm(chems, m, mod, i, j, envs)
```
<br/><br/>


```{R Single Environment Treatment Effects: Visualization, warning=FALSE}
# get datasets for panels A, B, C, D -------------------------------------------
mAA <- myrc[myrc$mpasp==0.0 & myrc$epo %in% c("SALT_A", "SALT_B") & !is.na(myrc$dw) & !is.na(myrc$reads_dw),]
mCC <- myrc[myrc$mpasp==0.8 & myrc$epo %in% c("SALT_A", "SALT_B") & !is.na(myrc$dw) & !is.na(myrc$reads_dw),]
mBB <- myrc[myrc$mpasp==0.0 & myrc$epo %in% c("COPR_A", "COPR_B") & !is.na(myrc$dw) & !is.na(myrc$reads_dw),]
mDD <- myrc[myrc$mpasp==0.8 & myrc$epo %in% c("COPR_A", "COPR_B") & !is.na(myrc$dw) & !is.na(myrc$reads_dw),]


# Set plotting controls --------------------------------------------------------
fitaxdatlimSALT <- c(-0.16*100, 0.45*100) #; min(c(mAA$dw, mCC$dw)); max(c(mAA$dw, mCC$dw))
fitaxdatlimCOPR <- c(-0.1*100, 0.57*100) #; min(c(mBB$dw, mDD$dw)); max(c(mBB$dw, mDD$dw))
fitaxlablim <- c(-0.1*100, 0.5*100) 
boxSALT <- c(0.2*100, 0.49*100) #; (boxSALT[2]-boxSALT[1]) / (fitaxdatlimSALT[2] - fitaxdatlimSALT[1])
boxCOPR <- c(0.275*100, 0.59*100) #; (boxCOPR[2]-boxCOPR[1]) / (fitaxdatlimCOPR[2] - fitaxdatlimCOPR[1])
treatlabSALT <- "NaCl Evol. Treatment"
treatlabCOPR <- expression(bold(CuSO["4"]*"  Evol. Treatment"))
fitnesslabCM <- "Fitness Change (%) in 0% Stress"
fitnesslabSALT <- "Fitness Change (%) in 80% NaCl"
fitnesslabCOPR <- expression(bold("Fitness Change (%) in 80% "*CuSO["4"]*""))
treatlist <- c("EH0","EH0_40","EH40","EH20_60","EH0_80","EH40_80","EH80")


# Create stats results backer --------------------------------------------------
myres_backer <- myres_est_SALT_0 
myres_backer[myres_backer < 0] <- -1
myres_backer[myres_backer > 0 | is.na(myres_backer)] <- 1
myres_backer <- get_lower_tri(round(myres_backer, 2))
melt_myres_backer <- reshape::melt(myres_backer)
melt_myres_backer$X1 <- factor(melt_myres_backer$X1, levels=treatlist)
melt_myres_backer$X2 <- factor(melt_myres_backer$X2, levels=treatlist)


# Modify stats results dataframes for plotting ---------------------------------
lsuffs <- c("AA", "CC", "BB", "DD")
lintabs <- c("SALT_0", "SALT_0.8", "COPR_0", "COPR_0.8")
for (i in 1:4) {
  assign("myres_est_temp", get(paste0("myres_est_", lintabs[i])))
  assign("myres_p_temp", get(paste0("myres_p_", lintabs[i])))
  myres_est_temp[which(myres_p_temp > 0.05)] <- NA
  myres_est_temp <- get_lower_tri(round(myres_est_temp*100, 0))
  melt_myres_est_temp <- reshape::melt(myres_est_temp)
  melt_myres_est_temp$X1 <- factor(melt_myres_est_temp$X1, levels=treatlist)
  melt_myres_est_temp$X2 <- factor(melt_myres_est_temp$X2, levels=treatlist)
  assign(paste0("melt_myres_est_", lsuffs[i]), melt_myres_est_temp)
}; rm(melt_myres_est_temp, myres_est_COPR_0, myres_est_COPR_0.8, myres_est_SALT_0, myres_est_SALT_0.8, myres_est_temp,
      myres_p_COPR_0, myres_p_COPR_0.8, myres_p_SALT_0, myres_p_SALT_0.8, myres_p_temp, i, lintabs, lsuffs, treatlist)


# Define plot function for panels A, B, C, D -----------------------------------
viopanel <- function(dwdata, statsdata, backerdata=melt_myres_backer, dcol="dw", 
                     fitlims, insetlims, fitaxlablims=fitaxlablim, fitaxstep=0.1*100,
                     treatlab, fitlab, tag, usepalette=mypalette){
  # main panel matter ------------------
  pZZ <- ggplot(dwdata, aes(x=treat, y=dwdata[,dcol]*100, group=treat, color=treat)) +
    geom_hline(yintercept=0, lty="dotted") + 
    geom_violin(fill="gray90", color="gray30", draw_quantiles=NULL, trim=T) +
    geom_jitter(width=0.15, height=0, alpha=0.35) + 
    geom_rug(sides="l" , alpha=0.7, length=unit(0.015, "npc")) +
    geom_point(stat="summary", fun="mean", color="black", cex=1.5) + 
    geom_point(stat="summary", fun="median", color="black", cex=3, pch=1) + 
    geom_errorbar(stat="summary", fun.data="mean_se",color="black", width=0.0, lwd=0.5)+
    scale_y_continuous(breaks=seq(fitaxlablims[1], fitaxlablims[2], by=fitaxstep), 
                       limits=c(fitlims[1], fitlims[2]),
                       labels=scales::number_format(accuracy=0.01*100))+
    scale_color_manual(values=usepalette) + 
    coord_flip() +
    ylab(fitlab) + 
    xlab(treatlab) +  
    labs(tag=tag)+
    theme_VJF() + 
    theme(legend.position="none")
  # stats results backer ---------------
  ppZZ <- ggplot(backerdata, aes(x=X1, y=X2, fill=value)) + 
    geom_tile(show.legend=F)+
    scale_y_discrete(position="right")+
    theme_tufte(base_family="Helvetica")+
    theme(axis.ticks=element_blank(), axis.title=element_blank(),
          axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, margin=margin(t=-2.5, b=-2.5), size=6),
          axis.text.y.right=element_text(hjust=0, vjust=0.5, margin=margin(l=-2.5, r=-2.5), size=6))+
    scale_fill_gradient2(low="transparent", high="gray80", mid="gray80", midpoint=0, space="Lab", name="Estimate", na.value="transparent")
  # Stats results ----------------------
  pppZZ <- ggplot(statsdata, aes(x=X1, y=X2, fill=value)) + 
    geom_tile(show.legend=F)+
    geom_text(aes(X1, X2, label=value), color="black", size=2, angle=0, fontface="bold") +
    scale_y_discrete(position="right")+
    theme_tufte(base_family="Helvetica")+
    theme(axis.ticks=element_blank(), axis.title=element_blank(),
          axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, margin=margin(t=-2.5, b=-2.5), size=6, face="bold"),
          axis.text.y.right=element_text(hjust=0, vjust=0.5, margin=margin(l=-2.5, r=-2.5), size=6, face="bold"))+
    scale_fill_gradient2(low="blue", high="red", mid="white", midpoint=0, space="Lab", name="Estimate", na.value="transparent")
  # Combine components -----------------
  pZZ <- pZZ + annotation_custom(ggplotGrob(ppZZ), xmin=0.5, xmax=3.5, ymin=insetlims[1], ymax=insetlims[2]); rm(ppZZ)
  pZZ <- pZZ + annotation_custom(ggplotGrob(pppZZ), xmin=0.5, xmax=3.5, ymin=insetlims[1], ymax=insetlims[2]); rm(pppZZ)
  return(pZZ)
}


# Visualization ----------------------------------------------------------------
pAA <- viopanel(dwdata=mAA, statsdata=melt_myres_est_AA, fitlims=fitaxdatlimSALT, insetlims=boxSALT, treatlab=treatlabSALT, fitlab=fitnesslabCM, tag="A")
pAA <- pAA + 
  annotate("text", x=1,y=16,label = "***", size = 6, fontface = "bold") +  # these significance values and those below are manually added -- if you change the data you must change these!
  annotate("text", x=2,y=11,label = "*", size = 6, fontface = "bold") +
  annotate("text", x=5,y=-12,label = "*", size = 6, fontface = "bold") +
  annotate("text", x=6,y=-9.5,label = "*", size = 6, fontface = "bold") +
  annotate("text", x=7,y=-16,label = "**", size = 6, fontface = "bold")
  
pCC <- viopanel(dwdata=mCC, statsdata=melt_myres_est_CC, fitlims=fitaxdatlimSALT, insetlims=boxSALT, treatlab=treatlabSALT, fitlab=fitnesslabSALT, tag="C")
pCC <- pCC +
  annotate("text", x=1,y=-10,label = "*", size = 6, fontface = "bold") +  
  annotate("text", x=4,y=23,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=5,y=45,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=6,y=40,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=7,y=42,label = "***", size = 6, fontface = "bold")

pBB <- viopanel(dwdata=mBB, statsdata=melt_myres_est_BB, fitlims=fitaxdatlimCOPR, insetlims=boxCOPR, treatlab=treatlabCOPR, fitlab=fitnesslabCM, tag="B")
pBB <- pBB  + 
  annotate("text", x=1,y=12,label = "***", size = 6, fontface = "bold") +  
  annotate("text", x=2,y=15,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=3,y=14.5,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=4,y=15,label = "***", size = 6, fontface = "bold")

pDD <- viopanel(dwdata=mDD, statsdata=melt_myres_est_DD, fitlims=fitaxdatlimCOPR, insetlims=boxCOPR, treatlab=treatlabCOPR, fitlab=fitnesslabCOPR, tag="D")
pDD <- pDD  + 
  annotate("text", x=1,y=14,label = "*", size = 6, fontface = "bold") +  
  annotate("text", x=3,y=21,label = "*", size = 6, fontface = "bold") +
  annotate("text", x=4,y=23,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=5,y=48,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=6,y=37,label = "***", size = 6, fontface = "bold") +
  annotate("text", x=7,y=56,label = "***", size = 6, fontface = "bold")

# Save outputs to file ---------------------------------------------------------
setwd(DIR_out); pdf(file="000_Figure_1.pdf", width=11, height=8.5)
cowplot::plot_grid(pAA, pBB, pCC, pDD, nrow=2); dev.off()

png("000_Figure_1.png", width=11, height=8.5, units = "in", res = 300)
cowplot::plot_grid(pAA, pBB, pCC, pDD, nrow=2); dev.off()

rm(mAA, mBB, mCC, mDD, melt_myres_est_AA, melt_myres_est_BB, melt_myres_est_CC, melt_myres_est_DD,
   myres_backer, myres0_est, myres0_p, pAA, pBB, pCC, pDD, boxCOPR, boxSALT, fitaxdatlimCOPR, fitaxdatlimSALT, fitaxlablim,
   fitnesslabCM, fitnesslabCOPR, fitnesslabSALT, treatlabCOPR, treatlabSALT) # tidy
```
<br/><br/>


```{R Cross-environment genetic correlation in fitness, warning = FALSE}
# prep plotting data -----------------------------------------------------------
# NaCl -----------------------------------------------------
# values -------------------------------
m <- myrcw[myrcw$treat == "EH0" & myrcw$epo %in% c("SALT_A", "SALT_B"),]
EH0in00 <- mean(m$dw_00, na.rm = T)
EH0in40 <- mean(m$dw_40, na.rm = T)
EH0in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("SALT_A", "SALT_B"),]
EH40in00 <- mean(m$dw_00, na.rm = T)
EH40in40 <- mean(m$dw_40, na.rm = T)
EH40in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH80" & myrcw$epo %in% c("SALT_A", "SALT_B"),]
EH80in00 <- mean(m$dw_00, na.rm = T)
EH80in40 <- mean(m$dw_40, na.rm = T)
EH80in80 <- mean(m$dw_80, na.rm = T); rm(m)

# x, y points --------------------------
a <- c(EH0in00, EH0in80)
aa <- c(EH80in00, EH80in80)
b <- c(EH0in00, EH0in40)
bb <- c(EH40in00, EH40in40)
c <- c(EH40in40, EH40in80)
cc <- c(EH80in40, EH80in80)
rm(EH0in00, EH0in40, EH0in80,
   EH40in00, EH40in40, EH40in80,
   EH80in00, EH80in40, EH80in80, m)


# CusO4 ----------------------------------------------------
# values -------------------------------
m <- myrcw[myrcw$treat == "EH0" & myrcw$epo %in% c("COPR_A", "COPR_B"),]
EH0in00 <- mean(m$dw_00, na.rm = T)
EH0in40 <- mean(m$dw_40, na.rm = T)
EH0in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("COPR_A", "COPR_B"),]
EH40in00 <- mean(m$dw_00, na.rm = T)
EH40in40 <- mean(m$dw_40, na.rm = T)
EH40in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH80" & myrcw$epo %in% c("COPR_A", "COPR_B"),]
EH80in00 <- mean(m$dw_00, na.rm = T)
EH80in40 <- mean(m$dw_40, na.rm = T)
EH80in80 <- mean(m$dw_80, na.rm = T)

# x, y points --------------------------
za <- c(EH0in00, EH0in80)
zaa <- c(EH80in00, EH80in80)
zb <- c(EH0in00, EH0in40)
zbb <- c(EH40in00, EH40in40)
zc <- c(EH40in40, EH40in80)
zcc <- c(EH80in40, EH80in80)
rm(EH0in00, EH0in40, EH0in80,
   EH40in00, EH40in40, EH40in80,
   EH80in00, EH80in40, EH80in80, m)

# multipanel  -----------------------------------------------------------
p1 <- ggplot()+
  xlim(min(a[1], aa[1], b[1], bb[1], c[1], cc[1], za[1], zaa[1], zb[1], zbb[1], zc[1], zcc[1])*1.10,
       max(a[1], aa[1], b[1], bb[1], c[1], cc[1], za[1], zaa[1], zb[1], zbb[1], zc[1], zcc[1])*1.10)+
  ylim(min(a[2], aa[2], b[2], bb[2], c[2], cc[2], za[2], zaa[2], zb[2], zbb[2], zc[2], zcc[2])*1.10,
       max(a[2], aa[2], b[2], bb[2], c[2], cc[2], za[2], zaa[2], zb[2], zbb[2], zc[2], zcc[2])*1.10)+
  geom_abline(slope = getline(b, bb)[1], intercept = getline(b, bb)[2], color = "blue", lty = "dotted") +
  geom_abline(slope = getline(zb, zbb)[1], intercept = getline(zb, zbb)[2], lty = "dotted", color = "blue", lwd = 0.5) +
  geom_segment(aes(x=b[1], xend=bb[1], y=b[2], yend=bb[2]), color = "blue", lwd = 1)+
  geom_segment(aes(x=zb[1], xend=zbb[1], y=zb[2], yend=zbb[2]), color = "blue", lwd = 1)+
  geom_point(aes(x = b[1], y = b[2]), color = "blue", size = 5)+
  geom_point(aes(x = bb[1], y = bb[2]), color = "blue", size = 5)+
  geom_point(aes(x = zb[1], y = zb[2]), color = "blue", size = 5, pch = 17)+
  geom_point(aes(x = zbb[1], y = zbb[2]), color = "blue", size = 5, pch = 17)+
  theme_VJF() + xlab("Fitness Change (%) in \n 0% Chemical Stress")+ylab("Fitness Change (%) in \n 40% Chemical Stress") + labs(tag="A")
p1 <- p1 + annotate("text", x=0.015,y=0.38,label = "Chemical Identity", size = 3, fontface = "bold")
p1 <- p1 + annotate("text", x=0.01,y=0.33,label = "NaCl", size = 3, fontface = "bold")
p1 <- p1 + annotate("text", x=0.012,y=0.35,label = expression(bold(""*CuSO["4"]*"")), size = 3, fontface = "bold")
p1 <- p1 + geom_point(aes(x = -0.005, y = 0.33), size = 5, color = "black")
p1 <- p1 + geom_point(aes(x = -0.005, y = 0.35), size = 5, color = "black", pch = 17)

p2 <- ggplot()+
  xlim(min(a[1], aa[1], b[1], bb[1], c[1], cc[1], za[1], zaa[1], zb[1], zbb[1], zc[1], zcc[1])*1.10,
       max(a[1], aa[1], b[1], bb[1], c[1], cc[1], za[1], zaa[1], zb[1], zbb[1], zc[1], zcc[1])*1.10)+
  ylim(min(a[2], aa[2], b[2], bb[2], c[2], cc[2], za[2], zaa[2], zb[2], zbb[2], zc[2], zcc[2])*1.10,
       max(a[2], aa[2], b[2], bb[2], c[2], cc[2], za[2], zaa[2], zb[2], zbb[2], zc[2], zcc[2])*1.10)+
  geom_abline(slope = getline(a, aa)[1], intercept = getline(a, aa)[2], color = "purple", lty = "dotted") +
  geom_abline(slope = getline(za, zaa)[1], intercept = getline(za, zaa)[2], lty = "dotted", color = "purple", lwd = 0.5) +
  geom_segment(aes(x=a[1], xend=aa[1], y=a[2], yend=aa[2]), color = "purple", lwd = 1)+
  geom_segment(aes(x=za[1], xend=zaa[1], y=za[2], yend=zaa[2]), color = "purple", lwd = 1)+
  geom_point(aes(x = a[1], y = a[2]), color = "purple", size = 5)+
  geom_point(aes(x = aa[1], y = aa[2]), color = "purple", size = 5)+
  geom_point(aes(x = za[1], y = za[2]), color = "purple", size = 5, pch = 17)+
  geom_point(aes(x = zaa[1], y = zaa[2]), color = "purple", size = 5, pch = 17)+
  theme_VJF() + xlab("Fitness Change (%) in \n 0% Chemical Stress")+ylab("Fitness Change (%) in \n 80% Chemical Stress")+ labs(tag="B")

p3 <- ggplot()+
  xlim(min(a[1], aa[1], b[1], bb[1], c[1], cc[1], za[1], zaa[1], zb[1], zbb[1], zc[1], zcc[1])*1.10,
       max(a[1], aa[1], b[1], bb[1], c[1], cc[1], za[1], zaa[1], zb[1], zbb[1], zc[1], zcc[1])*1.10)+
  ylim(min(a[2], aa[2], b[2], bb[2], c[2], cc[2], za[2], zaa[2], zb[2], zbb[2], zc[2], zcc[2])*1.10,
       max(a[2], aa[2], b[2], bb[2], c[2], cc[2], za[2], zaa[2], zb[2], zbb[2], zc[2], zcc[2])*1.10)+
  geom_abline(slope = getline(c, cc)[1], intercept = getline(c, cc)[2], color = "red", lty = "dotted") +
  geom_abline(slope = getline(zc, zcc)[1], intercept = getline(zc, zcc)[2], lty = "dotted", color = "red", lwd = 0.5) +
  geom_segment(aes(x=c[1], xend=cc[1], y=c[2], yend=cc[2]), color = "red", lwd = 1)+
  geom_segment(aes(x=zc[1], xend=zcc[1], y=zc[2], yend=zcc[2]), color = "red", lwd = 1)+
  geom_point(aes(x = c[1], y = c[2]), color = "red", size = 5)+
  geom_point(aes(x = cc[1], y = cc[2]), color = "red", size = 5)+
  geom_point(aes(x = zc[1], y = zc[2]), color = "red", size = 5, pch = 17)+
  geom_point(aes(x = zcc[1], y = zcc[2]), color = "red", size = 5, pch = 17)+
  theme_VJF()+xlab("Fitness Change (%) in \n 40% Chemical Stress")+ylab("Fitness Change (%) in \n 80% Chemical Stress")+ labs(tag="C")

# Save outputs to file ---------------------------------------------------------
setwd(DIR_out); pdf(file="000_Figure_2.pdf", width=8.5, height=5)
cowplot::plot_grid(p1, p2, p3, nrow=1); dev.off()

png("000_Figure_2.png", width=8.5, height=5, units = "in", res = 300)
cowplot::plot_grid(p1, p2, p3, nrow=1); dev.off()

rm(p1, p2, p3, a, aa, b, bb, c, cc, za, zaa, zb, zbb, zc, zcc)
```
<br/><br/>


```{R Adaptation and fitness costs: Tables, warning = FALSE}
# table 1 ----------------------------------------------------------------------
mymat <- matrix(nrow = 4, ncol = 2)
m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[1,1] <- nrow(m)
mymat[1,2] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[2,2] <- nrow(m)
mymat[2,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[3,1] <- nrow(m)
mymat[3,2] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[4,2] <- nrow(m)
mymat[4,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),]); rm(m)
mymat; rm(mymat) # Just treatments EH0 and EH80



# table S4 SALT HALF -----------------------------------------------------------
mymat <- matrix(nrow = 9, ncol = 3)
m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[1,1] <- nrow(m)
mymat[1,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),])
mymat[1,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0_40"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[2,1] <- nrow(m)
mymat[2,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),])
mymat[2,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0_40"),]
m <- m[!is.na(m$dw_40),]
m <- m[m$dw_40 >= 0.0216,]
mymat[3,2] <- nrow(m)
mymat[3,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[3,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH40"),]
m <- m[!is.na(m$dw_40),]
m <- m[m$dw_40 >= 0.0216,]
mymat[4,2] <- nrow(m)
mymat[4,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[4,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0_80"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[5,1] <- nrow(m)
mymat[5,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),])
mymat[5,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0_80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[6,3] <- nrow(m)
mymat[6,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[6,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH40_80"),]
m <- m[!is.na(m$dw_40),]
m <- m[m$dw_40 >= 0.0216,]
mymat[7,2] <- nrow(m)
mymat[7,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[7,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH40_80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[8,3] <- nrow(m)
mymat[8,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[8,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),]); rm(m)

m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[9,3] <- nrow(m)
mymat[9,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[9,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),]); rm(m)
mymat; rm(mymat) # All treatments


# table S4 COPR HALF -----------------------------------------------------------
mymat <- matrix(nrow = 9, ncol = 3)
m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[1,1] <- nrow(m)
mymat[1,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),])
mymat[1,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0_40"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[2,1] <- nrow(m)
mymat[2,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),])
mymat[2,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0_40"),]
m <- m[!is.na(m$dw_40),]
m <- m[m$dw_40 >= 0.0216,]
mymat[3,2] <- nrow(m)
mymat[3,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[3,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH40"),]
m <- m[!is.na(m$dw_40),]
m <- m[m$dw_40 >= 0.0216,]
mymat[4,2] <- nrow(m)
mymat[4,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[4,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0_80"),]
m <- m[!is.na(m$dw_00),]
m <- m[m$dw_00 >= 0.0216,]
mymat[5,1] <- nrow(m)
mymat[5,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),])
mymat[5,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0_80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[6,3] <- nrow(m)
mymat[6,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[6,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH40_80"),]
m <- m[!is.na(m$dw_40),]
m <- m[m$dw_40 >= 0.0216,]
mymat[7,2] <- nrow(m)
mymat[7,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[7,3] <- nrow(m[which(m$dw_80 <= -0.0216),]) + nrow(m[is.na(m$dw_80),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH40_80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[8,3] <- nrow(m)
mymat[8,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[8,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),]); rm(m)

m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH80"),]
m <- m[!is.na(m$dw_80),]
m <- m[m$dw_80 >= 0.0216,]
mymat[9,3] <- nrow(m)
mymat[9,1] <- nrow(m[which(m$dw_00 <= -0.0216),]) + nrow(m[is.na(m$dw_00),])
mymat[9,2] <- nrow(m[which(m$dw_40 <= -0.0216),]) + nrow(m[is.na(m$dw_40),]); rm(m)
mymat; rm(mymat) # all treatments
```
<br/><br/>


```{R Adaptation and fitness costs: Figure Legend, warning = FALSE}
m <- myrcw[myrcw$treat %in% c("EH0", "EH40", "EH80"),]
legp <- ggplot(data = m, aes( x = dw_00, y = dw_80, color = treat))+
  geom_point(size = 2) + theme_VJF() + scale_color_manual(values = mypalette[c(1,3,7)]) + labs(color = "Treatment") + guides(color = guide_legend(reverse = T))+
  theme(legend.title = element_text(size = 7), 
          legend.text = element_text(size = 7))
legp <- get_legend(legp); rm(m)
```
<br/><br/>


```{R Adaptation and fitness costs: Figure, warning = FALSE}
# NaCl -------------------------------------------------------------------------
# Prep plot data -------------------------------------------
m <- myrcw[myrcw$epo %in% c("SALT_A", "SALT_B") & myrcw$treat %in% c("EH0", "EH40", "EH80"),]
mm <- m[,c("treat", "dw_00", "dw_40", "dw_80")]
colnames(mm) <- c("treat", "0%", "40%", "80%")
mm$indiv <- seq(1:nrow(mm))
mm <- mm[mm$indiv != 48,] # mm[which(mm$dw_00 == min(mm$dw_00, na.rm  = T)),]
mm <- mm[mm$indiv != 28,] # mm[which(mm$dw_40 == min(mm$dw_40, na.rm  = T)),]
limmin <- min(c(mm$"0%", mm$"40%", mm$"80%"), na.rm = T) - 0.01
limmax <- max(c(mm$"0%", mm$"40%", mm$"80%"), na.rm = T) + 0.01
mm <- melt(mm, id = c("treat", "indiv"))

# Create plot Panels ---------------------------------------
p1 <- ggplot(mm[mm$treat == "EH0",], aes(x = variable, y = value, color = treat, group = indiv))+
  geom_abline(slope=0)+
  geom_point(alpha = 0.35)+
  geom_line(alpha = 0.35)+
  # geom_abline(slope=0, intercept = -0.0216, lty = "dotted")+
  # geom_abline(slope=0, intercept = 0.0216, lty = "dotted")+
  scale_color_manual(values = mypalette[1])+
  ylim(c(limmin, limmax))+
  theme_VJF()+
  theme(legend.position = "none")+
  xlab("") + ylab("Fitness Change") + labs(tag = "A")
p2 <- ggplot(mm[mm$treat == "EH40",], aes(x = variable, y = value, color = treat, group = indiv))+
  geom_abline(slope=0)+
  geom_point(alpha = 0.35)+
  geom_line(alpha = 0.35)+
  # geom_abline(slope=0, intercept = -0.0216, lty = "dotted")+
  # geom_abline(slope=0, intercept = 0.0216, lty = "dotted")+
  scale_color_manual(values = mypalette[3])+
  ylim(c(limmin, limmax))+
  theme_VJF()+
  theme(legend.position = "none")+
  xlab("NaCl Percent") + ylab("") + labs(tag = "B")
p3 <- ggplot(mm[mm$treat == "EH80",], aes(x = variable, y = value, color = treat, group = indiv))+
  geom_abline(slope=0)+
  geom_point(alpha = 0.35)+
  geom_line(alpha = 0.35)+
  # geom_abline(slope=0, intercept = -0.0216, lty = "dotted")+
  # geom_abline(slope=0, intercept = 0.0216, lty = "dotted")+
  scale_color_manual(values = mypalette[7])+
  ylim(c(limmin, limmax))+
  theme_VJF()+
  theme(legend.position = "none")+
  xlab("") + ylab("") + labs(tag = "C")
p3 <- p3 + annotation_custom(legp, xmin = -0.8, ymin = 0.28)

# CuSO4 ------------------------------------------------------------------------
# Prep plot data -------------------------------------------
m <- myrcw[myrcw$epo %in% c("COPR_A", "COPR_B") & myrcw$treat %in% c("EH0", "EH40", "EH80"),]
zmm <- m[,c("treat", "dw_00", "dw_40", "dw_80")]
colnames(zmm) <- c("treat", "0%", "40%", "80%")
zmm$indiv <- seq(1:nrow(zmm))
zmm <- zmm[zmm$indiv != 48,] # zmm[which(zmm$dw_00 == min(zmm$dw_00, na.rm  = T)),]
zmm <- zmm[zmm$indiv != 28,] # zmm[which(zmm$dw_40 == min(zmm$dw_40, na.rm  = T)),]
lizmmin <- min(c(zmm$"0%", zmm$"40%", zmm$"80%"), na.rm = T) - 0.01
lizmmax <- max(c(zmm$"0%", zmm$"40%", zmm$"80%"), na.rm = T) + 0.01
zmm <- melt(zmm, id = c("treat", "indiv"))

# Create plot Panels ---------------------------------------
p4 <- ggplot(zmm[zmm$treat == "EH0",], aes(x = variable, y = value, color = treat, group = indiv))+
  geom_abline(slope=0)+
  geom_point(alpha = 0.35)+
  geom_line(alpha = 0.35)+
  # geom_abline(slope=0, intercept = -0.0216, lty = "dotted")+
  # geom_abline(slope=0, intercept = 0.0216, lty = "dotted")+
  scale_color_manual(values = mypalette[1])+
  ylim(c(lizmmin, lizmmax))+
  theme_VJF()+
  theme(legend.position = "none")+
  xlab("") + ylab("Fitness Change") + labs(tag = "D")
p5 <- ggplot(zmm[zmm$treat == "EH40",], aes(x = variable, y = value, color = treat, group = indiv))+
  geom_abline(slope=0)+
  geom_point(alpha = 0.35)+
  geom_line(alpha = 0.35)+
  # geom_abline(slope=0, intercept = -0.0216, lty = "dotted")+
  # geom_abline(slope=0, intercept = 0.0216, lty = "dotted")+
  scale_color_manual(values = mypalette[3])+
  ylim(c(lizmmin, lizmmax))+
  theme_VJF()+
  theme(legend.position = "none")+
  xlab(expression(bold(CuSO["4"]*" Percent"))) + ylab("") + labs(tag = "E")
p6 <- ggplot(zmm[zmm$treat == "EH80",], aes(x = variable, y = value, color = treat, group = indiv))+
  geom_abline(slope=0)+
  geom_point(alpha = 0.35)+
  geom_line(alpha = 0.35)+
  # geom_abline(slope=0, intercept = -0.0216, lty = "dotted")+
  # geom_abline(slope=0, intercept = 0.0216, lty = "dotted")+
  scale_color_manual(values = mypalette[7])+
  ylim(c(lizmmin, lizmmax))+
  theme_VJF()+
  theme(legend.position = "none")+
  xlab("") + ylab("") + labs(tag = "F")

# Save outputs to file ---------------------------------------------------------
setwd(DIR_out); png("000_Figure_3.png", width = 6*1.25, height = 5*1.25, units = "in", res = 300)
grid.arrange(p1,p2,p3, 
             p4,p5,p6,
             ncol = 3)
dev.off()

setwd(DIR_out); pdf("000_Figure_3.pdf", width = 6*1.25, height = 5*1.25)
grid.arrange(p1,p2,p3, 
             p4,p5,p6,
             ncol = 3)
dev.off()
```
<br/><br/>


```{R Costs of Generalization 0,80: legend, warning = FALSE}
m <- myrcw[myrcw$treat %in% c("EH0_40", "EH20_60", "EH0_80", "EH40_80"),]
legp <- ggplot(data = m, aes( x = dw_00, y = dw_80, color = treat))+
  geom_point(size = 1.5) + theme_VJF() + scale_color_manual(values = mypalette[c(2,4,5,6)]) + labs(color = "Treatment") + guides(color = guide_legend(reverse = T))+
  theme(legend.title = element_text(size = 7), 
          legend.text = element_text(size = 7))
legp <- get_legend(legp); rm(m)
```
<br/><br/>


```{R Costs of Generalization 0,80: Figure panels A and C, warning = FALSE}
# get value data ---------------------------------------------------------------
m <- myrcw[myrcw$treat == "EH0" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH0in00 <- mean(m$dw_00, na.rm = T)
EH0in40 <- mean(m$dw_40, na.rm = T)
EH0in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH40in00 <- mean(m$dw_00, na.rm = T)
EH40in40 <- mean(m$dw_40, na.rm = T)
EH40in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH80" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH80in00 <- mean(m$dw_00, na.rm = T)
EH80in40 <- mean(m$dw_40, na.rm = T)
EH80in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH0_80in00 <- mean(m$dw_00, na.rm = T)
EH0_80in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH0_40in00 <- mean(m$dw_00, na.rm = T)
EH0_40in40 <- mean(m$dw_40, na.rm = T)
EH0_40in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH40_80" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH40_80in0 <- mean(m$dw_00, na.rm = T)
EH40_80in40 <- mean(m$dw_40, na.rm = T)
EH40_80in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH20_60" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH20_60in00 <- mean(m$dw_00, na.rm = T)
EH20_60in80 <- mean(m$dw_80, na.rm = T)

# get point data ---------------------------------------------------------------
a <- c(EH0_80in00, EH0_80in80)
z <- c(EH20_60in00, EH20_60in80)
n <- c(EH0_40in00, EH0_40in80)
p <- c(EH40_80in0, EH40_80in80)
q <- c(EH40in00, EH40in80)
b <- c(EH0in00, EH0in80)
c <- c(EH80in00, EH80in80)
rm(EH0in00, EH0in40, EH0in80,
   EH40in00, EH40in40, EH40in80,
   EH80in00, EH80in40, EH80in80,
   EH0_80in00, EH0_0in80,
   EH0_40in00, EH0_40in40, EH0_40in80,
   EH40_80in0, EH40_80in40, EH40_80in80,
   EH20_60in00, EH20_60in80, m)

# get sign and dist ------------------------------------------------------------
aaa <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_80")]
aaa <- aaa[!is.na(aaa$dw_00) & !is.na(aaa$dw_80),]
aaa$dist <- apply(cbind(aaa$dw_00, aaa$dw_80), 1, dist2d, b=b, c=c)
aaa$sign <- apply(cbind(aaa$dw_00, aaa$dw_80), 1, lineside, b=b, c=c)

zzz <- myrcw[myrcw$treat == "EH20_60" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_80")]
zzz <- zzz[!is.na(zzz$dw_00) & !is.na(zzz$dw_80),]
zzz$dist <- apply(cbind(zzz$dw_00, zzz$dw_80), 1, dist2d, b=b, c=c)
zzz$sign <- apply(cbind(zzz$dw_00, zzz$dw_80), 1, lineside, b=b, c=c)

nnn <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_80")]
nnn <- nnn[!is.na(nnn$dw_00) & !is.na(nnn$dw_80),]
nnn$dist <- apply(cbind(nnn$dw_00, nnn$dw_80), 1, dist2d, b=b, c=c)
nnn$sign <- apply(cbind(nnn$dw_00, nnn$dw_80), 1, lineside, b=b, c=c)

ppp <- myrcw[myrcw$treat == "EH40_80" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_80")]
ppp <- ppp[!is.na(ppp$dw_00) & !is.na(ppp$dw_80),]
ppp$dist <- apply(cbind(ppp$dw_00, ppp$dw_80), 1, dist2d, b=b, c=c)
ppp$sign <- apply(cbind(ppp$dw_00, ppp$dw_80), 1, lineside, b=b, c=c)

qqq <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_80")]
qqq <- qqq[!is.na(qqq$dw_00) & !is.na(qqq$dw_80),]
qqq$dist <- apply(cbind(qqq$dw_00, qqq$dw_80), 1, dist2d, b=b, c=c)
qqq$sign <- apply(cbind(qqq$dw_00, qqq$dw_80), 1, lineside, b=b, c=c)

dist2d(a, b, c) # distance to line for generalist
# nrow(aaa[aaa$sign < 0,])/nrow(aaa) # prop on side 1
# nrow(aaa[aaa$sign > 0,])/nrow(aaa) # prop on side 2

dist2d(z, b, c) # distance to line for generalist
# nrow(zzz[zzz$sign < 0,])/nrow(zzz) # prop on side 1
# nrow(zzz[zzz$sign > 0,])/nrow(zzz) # prop on side 2

dist2d(n, b, c) # distance to line for generalist
# nrow(nnn[nnn$sign < 0,])/nrow(nnn) # prop on side 1
# nrow(nnn[nnn$sign > 0,])/nrow(nnn) # prop on side 2

dist2d(p, b, c) # distance to line for generalist
# nrow(ppp[ppp$sign < 0,])/nrow(ppp) # prop on side 1
# nrow(ppp[ppp$sign > 0,])/nrow(ppp) # prop on side 2

dist2d(q, b, c) # distance to line for generalist
# nrow(qqq[qqq$sign < 0,])/nrow(qqq) # prop on side 1
# nrow(qqq[qqq$sign > 0,])/nrow(qqq) # prop on side 2

# panel a ----------------------------------------------------------------------
p1 <- ggplot(data = aaa, aes(x = dw_00, y = dw_80))+ geom_rug(data=aaa, aes(x = dw_00, y = dw_80), color =  ggplot2::alpha(mypalette[5], 0.5))+
  xlim(min(b[1], c[1], aaa$dw_00, zzz$dw_00, nnn$dw_00, ppp$dw_00, qqq$dw_00)*1.10,
       max(b[1], c[1], aaa$dw_00, zzz$dw_00, nnn$dw_00, ppp$dw_00, qqq$dw_00)*1.10) +
  ylim(min(b[2], c[2], aaa$dw_80, zzz$dw_80, nnn$dw_00, ppp$dw_00, qqq$dw_80)*1.10,
       max(b[2], c[2], aaa$dw_80, zzz$dw_80, nnn$dw_80, ppp$dw_80, qqq$dw_80)*1.10)+
  geom_abline(slope = getline(b, c)[1], intercept = getline(b, c)[2], lty = "dotdash") +
  geom_point(pch = 1, color = mypalette[5], size = 0.75)+
  geom_point(data =zzz, aes(x = dw_00, y = dw_80), color = mypalette[4], pch = 1, size = 0.75)+ geom_rug(data=zzz, aes(x = dw_00, y = dw_80), color =  ggplot2::alpha(mypalette[4], 0.5))+
  geom_point(data =nnn, aes(x = dw_00, y = dw_80), color = mypalette[2], pch = 1, size = 0.75)+ geom_rug(data=nnn, aes(x = dw_00, y = dw_80), color =  ggplot2::alpha(mypalette[2], 0.5))+
  geom_point(data =ppp, aes(x = dw_00, y = dw_80), color = mypalette[6], pch = 1, size = 0.75)+ geom_rug(data=ppp, (aes(x = dw_00, y = dw_80)), color =  ggplot2::alpha(mypalette[6], 0.5))+
  # geom_point(data =qqq, aes(x = dw_00, y = dw_80), color = mypalette[3], pch = 1, size = 0.75)+ geom_rug(data=qqq, (aes(x = dw_00, y = dw_80)), color =  ggplot2::alpha(mypalette[3], 0.5))+
  geom_point(x=a[1], y=a[2], fill = mypalette[5], size = 3, pch = 21)+
  geom_point(x=z[1], y=z[2], fill = mypalette[4], size = 3, pch = 21)+
  geom_point(x=n[1], y=n[2], fill = mypalette[2], size = 3, pch = 21)+
  geom_point(x=p[1], y=p[2], fill = mypalette[6], size = 3, pch = 21)+
  # geom_point(x=q[1], y=q[2], fill = mypalette[3], size = 3, pch = 21)+
  geom_point(x=b[1], y=b[2], color = "black", size = 2)+
  geom_point(x=c[1], y=c[2], color = "black", size = 2)+
  theme_VJF()+ xlab("Fitness Change (%) in 0% NaCl")+ylab("Fitness Change (%) in 80% NaCl")+ labs(tag="A")
rm(a,z,n,p,q,b,c)

# panel c ----------------------------------------------------------------------
p2 <- ggplot()+
  geom_vline(aes(xintercept = 0), color = "black", lty = "dotdash")+
  geom_vline(aes(xintercept = mean(aaa$dist*aaa$sign)), lty = "dotted", color = mypalette[5])+
  geom_vline(aes(xintercept = mean(zzz$dist*zzz$sign)), lty = "dotted", color = mypalette[4])+
  geom_vline(aes(xintercept = mean(nnn$dist*nnn$sign)), lty = "dotted", color = mypalette[2])+
  geom_vline(aes(xintercept = mean(ppp$dist*ppp$sign)), lty = "dotted", color = mypalette[6])+
  # geom_vline(aes(xintercept = mean(qqq$dist*qqq$sign)), lty = "dotted", color = mypalette[3])+
  geom_density(data = aaa, aes(x = dist*sign), color = mypalette[5]) + geom_rug(data=aaa, aes(x=dist*sign), color =  ggplot2::alpha(mypalette[5], 0.5))+
  geom_density(data = zzz, aes(x = dist*sign), color = mypalette[4]) + geom_rug(data=zzz, aes(x=dist*sign), color =  ggplot2::alpha(mypalette[4], 0.5))+
  geom_density(data = nnn, aes(x = dist*sign), color = mypalette[2]) + geom_rug(data=nnn, aes(x=dist*sign), color =  ggplot2::alpha(mypalette[2], 0.5))+
  geom_density(data = ppp, aes(x = dist*sign), color = mypalette[6]) + geom_rug(data=ppp, (aes(x=dist*sign)), color =  ggplot2::alpha(mypalette[6], 0.5))+
  # geom_density(data = qqq, aes(x = dist*sign), color = mypalette[3]) + geom_rug(data=qqq, (aes(x=dist*sign)), color =  ggplot2::alpha(mypalette[3], 0.5))+
  theme_VJF()+  xlab("Cost") + ylab("Density")+ labs(tag="C")

# model for table S7 -----------------------------------------------------------
aaa$treat <- "EH0_80"
zzz$treat <- "EH20_60"
nnn$treat <- "EH0_40"
ppp$treat <- "EH40_80"
tempdata <- rbind(aaa, zzz, nnn, ppp)
tempdata$cost <- tempdata$dist*tempdata$sign
tempdata$treat <- factor(tempdata$treat, levels = c("EH0_40", "EH20_60", "EH0_80", "EH40_80"))
# hist(tempdata$cost)
mymod <- lm(cost ~ treat + 0, data = tempdata)
summary(mymod)
setwd(DIR_out); print(tab_model(mymod, digits=5, digits.p=8, show.stat=T, wrap.labels=100,
                      file=paste0("000_Table_S7.html")))
rm(mymod)

# significant individuals ------------------------------------------------------
print("total")
table(tempdata$treat)
print("n with cost")
table(tempdata[tempdata$cost <= -0.0216,]$treat)
print("p with cost")
table(tempdata[tempdata$cost <= -0.0216,]$treat)/table(tempdata$treat)
print("n neutral")
table(tempdata[tempdata$cost > -0.0216 & tempdata$cost < 0.0216,]$treat)
print("p neutral")
table(tempdata[tempdata$cost > -0.0216 & tempdata$cost < 0.0216,]$treat)/table(tempdata$treat)
print("n with benefit")
table(tempdata[tempdata$cost >= 0.0216,]$treat)  
print("p with benefit")
table(tempdata[tempdata$cost >= 0.0216,]$treat)/table(tempdata$treat)
rm(tempdata)
```
<br/><br/>


```{R Costs of Generalization 0,80: Figure panels B and D, warning = FALSE}
# get value data ---------------------------------------------------------------
m <- myrcw[myrcw$treat == "EH0" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH0in00 <- mean(m$dw_00, na.rm = T)
EH0in40 <- mean(m$dw_40, na.rm = T)
EH0in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH40in00 <- mean(m$dw_00, na.rm = T)
EH40in40 <- mean(m$dw_40, na.rm = T)
EH40in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH80" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH80in00 <- mean(m$dw_00, na.rm = T)
EH80in40 <- mean(m$dw_40, na.rm = T)
EH80in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH0_80in00 <- mean(m$dw_00, na.rm = T)
EH0_80in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH0_40in00 <- mean(m$dw_00, na.rm = T)
EH0_40in40 <- mean(m$dw_40, na.rm = T)
EH0_40in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH40_80" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH40_80in0 <- mean(m$dw_00, na.rm = T)
EH40_80in40 <- mean(m$dw_40, na.rm = T)
EH40_80in80 <- mean(m$dw_80, na.rm = T)

m <- myrcw[myrcw$treat == "EH20_60" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH20_60in00 <- mean(m$dw_00, na.rm = T)
EH20_60in80 <- mean(m$dw_80, na.rm = T)


# get point data ---------------------------------------------------------------
a <- c(EH0_80in00, EH0_80in80)
z <- c(EH20_60in00, EH20_60in80)
n <- c(EH0_40in00, EH0_40in80)
p <- c(EH40_80in0, EH40_80in80)
q <- c(EH40in00, EH40in80)
b <- c(EH0in00, EH0in80)
c <- c(EH80in00, EH80in80)
rm(EH0in00, EH0in40, EH0in80,
   EH40in00, EH40in40, EH40in80,
   EH80in00, EH80in40, EH80in80,
   EH0_80in00, EH0_80in80,
   EH0_40in00, EH0_40in40, EH0_40in80,
   EH40_80in0, EH40_80in40, EH40_80in80,
   EH20_60in00, EH20_60in80, m)

# get sign and dist ------------------------------------------------------------
zaaa <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_80")]
zaaa <- zaaa[!is.na(zaaa$dw_00) & !is.na(zaaa$dw_80),]
zaaa$dist <- apply(cbind(zaaa$dw_00, zaaa$dw_80), 1, dist2d, b=b, c=c)
zaaa$sign <- apply(cbind(zaaa$dw_00, zaaa$dw_80), 1, lineside, b=b, c=c)

zzzz <- myrcw[myrcw$treat == "EH20_60" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_80")]
zzzz <- zzzz[!is.na(zzzz$dw_00) & !is.na(zzzz$dw_80),]
zzzz$dist <- apply(cbind(zzzz$dw_00, zzzz$dw_80), 1, dist2d, b=b, c=c)
zzzz$sign <- apply(cbind(zzzz$dw_00, zzzz$dw_80), 1, lineside, b=b, c=c)

znnn <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_80")]
znnn <- znnn[!is.na(znnn$dw_00) & !is.na(znnn$dw_80),]
znnn$dist <- apply(cbind(znnn$dw_00, znnn$dw_80), 1, dist2d, b=b, c=c)
znnn$sign <- apply(cbind(znnn$dw_00, znnn$dw_80), 1, lineside, b=b, c=c)

zppp <- myrcw[myrcw$treat == "EH40_80" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_80")]
zppp <- zppp[!is.na(zppp$dw_00) & !is.na(zppp$dw_80),]
zppp$dist <- apply(cbind(zppp$dw_00, zppp$dw_80), 1, dist2d, b=b, c=c)
zppp$sign <- apply(cbind(zppp$dw_00, zppp$dw_80), 1, lineside, b=b, c=c)

zqqq <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_80")]
zqqq <- zqqq[!is.na(zqqq$dw_00) & !is.na(zqqq$dw_80),]
zqqq$dist <- apply(cbind(zqqq$dw_00, zqqq$dw_80), 1, dist2d, b=b, c=c)
zqqq$sign <- apply(cbind(zqqq$dw_00, zqqq$dw_80), 1, lineside, b=b, c=c)

dist2d(a, b, c) # distance to line for generalist
# nrow(zaaa[zaaa$sign < 0,])/nrow(zaaa) # prop on side 1
# nrow(zaaa[zaaa$sign > 0,])/nrow(zaaa) # prop on side 2

dist2d(z, b, c) # distance to line for generalist
# nrow(zzzz[zzzz$sign < 0,])/nrow(zzzz) # prop on side 1
# nrow(zzzz[zzzz$sign > 0,])/nrow(zzzz) # prop on side 2

dist2d(n, b, c) # distance to line for generalist
# nrow(znnn[znnn$sign < 0,])/nrow(znnn) # prop on side 1
# nrow(znnn[znnn$sign > 0,])/nrow(znnn) # prop on side 2

dist2d(p, b, c) # distance to line for generalist
# nrow(zppp[zppp$sign < 0,])/nrow(zppp) # prop on side 1
# nrow(zppp[zppp$sign > 0,])/nrow(zppp) # prop on side 2

dist2d(q, b, c) # distance to line for generalist
# nrow(zqqq[zqqq$sign < 0,])/nrow(zqqq) # prop on side 1
# nrow(zqqq[zqqq$sign > 0,])/nrow(zqqq) # prop on side 2

# panel B ----------------------------------------------------------------------
p3 <- ggplot(data = zaaa, aes(x = dw_00, y = dw_80))+geom_rug(data=zaaa, aes(x = dw_00, y = dw_80), color =  ggplot2::alpha(mypalette[5], 0.5))+
  xlim(min(b[1], c[1], zaaa$dw_00, zzzz$dw_00, znnn$dw_00, zppp$dw_00, zqqq$dw_00)*1.10,
       max(b[1], c[1], zaaa$dw_00, zzzz$dw_00, znnn$dw_00, zppp$dw_00, zqqq$dw_00)*1.10) +
  ylim(min(b[2], c[2], zaaa$dw_80, zzzz$dw_80, znnn$dw_00, zppp$dw_00, zqqq$dw_80)*1.10,
       max(b[2], c[2], zaaa$dw_80, zzzz$dw_80, znnn$dw_80, zppp$dw_80, zqqq$dw_80)*1.10)+
  geom_abline(slope = getline(b, c)[1], intercept = getline(b, c)[2], lty = "dotdash") +
  geom_point(pch = 1, color = mypalette[5], size = 0.75)+
  geom_point(data =zzzz, aes(x = dw_00, y = dw_80), color = mypalette[4], pch = 1, size = 0.75)+geom_rug(data=zzzz, aes(x = dw_00, y = dw_80), color =  ggplot2::alpha(mypalette[4], 0.5))+
  geom_point(data =znnn, aes(x = dw_00, y = dw_80), color = mypalette[2], pch = 1, size = 0.75)+geom_rug(data=znnn, aes(x = dw_00, y = dw_80), color =  ggplot2::alpha(mypalette[2], 0.5))+
  geom_point(data =zppp, aes(x = dw_00, y = dw_80), color = mypalette[6], pch = 1, size = 0.75)+geom_rug(data=zppp, (aes(x = dw_00, y = dw_80)), color =  ggplot2::alpha(mypalette[6], 0.5))+
  # geom_point(data =zqqq, aes(x = dw_00, y = dw_80), color = mypalette[3], pch = 1, size = 0.75)+geom_rug(data=zqqq, (aes(x = dw_00, y = dw_80)), color =  ggplot2::alpha(mypalette[3], 0.5))+
  geom_point(x=a[1], y=a[2], fill = mypalette[5], size = 3, pch = 21)+
  geom_point(x=z[1], y=z[2], fill = mypalette[4], size = 3, pch = 21)+
  geom_point(x=n[1], y=n[2], fill = mypalette[2], size = 3, pch = 21)+
  geom_point(x=p[1], y=p[2], fill = mypalette[6], size = 3, pch = 21)+
  # geom_point(x=q[1], y=q[2], fill = mypalette[3], size = 3, pch = 21)+
  geom_point(x=b[1], y=b[2], color = "black", size = 2)+
  geom_point(x=c[1], y=c[2], color = "black", size = 2)+
  theme_VJF()+ xlab(expression(bold("Fitness Change (%) in 0% "*CuSO["4"]*"")))+ylab(expression(bold("Fitness Change (%) in 80% "*CuSO["4"]*"")))+ labs(tag="B")
p3 <- p3 + annotation_custom(legp, xmin = 0.06, ymin = 0.35)
rm(a,z,n,p,q,b,c)

# panel D ----------------------------------------------------------------------
p4 <- ggplot()+
  geom_vline(aes(xintercept = 0), color = "black", lty = "dotdash")+
  geom_vline(aes(xintercept = mean(zaaa$dist*zaaa$sign)), lty = "dotted", color = mypalette[5])+
  geom_vline(aes(xintercept = mean(zzzz$dist*zzzz$sign)), lty = "dotted", color = mypalette[4])+
  geom_vline(aes(xintercept = mean(znnn$dist*znnn$sign)), lty = "dotted", color = mypalette[2])+
  geom_vline(aes(xintercept = mean(zppp$dist*zppp$sign)), lty = "dotted", color = mypalette[6])+
  # geom_vline(aes(xintercept = mean(zqqq$dist*zqqq$sign)), lty = "dotted", color = mypalette[3])+
  geom_density(data = zaaa, aes(x = dist*sign), color = mypalette[5]) + geom_rug(data=zaaa, aes(x=dist*sign), color =  ggplot2::alpha(mypalette[5], 0.5))+
  geom_density(data = zzzz, aes(x = dist*sign), color = mypalette[4]) + geom_rug(data=zzzz, aes(x=dist*sign), color =  ggplot2::alpha(mypalette[4], 0.5))+
  geom_density(data = znnn, aes(x = dist*sign), color = mypalette[2]) + geom_rug(data=znnn, aes(x=dist*sign), color =  ggplot2::alpha(mypalette[2], 0.5))+
  geom_density(data = zppp, aes(x = dist*sign), color = mypalette[6]) + geom_rug(data=zppp, (aes(x=dist*sign)), color =  ggplot2::alpha(mypalette[6], 0.5))+
  # geom_density(data = zqqq, aes(x = dist*sign), color = mypalette[3]) + geom_rug(data=zqqq, (aes(x=dist*sign)), color =  ggplot2::alpha(mypalette[3], 0.5))+
  theme_VJF() + xlab("Cost")+ labs(tag="D")

# create full figure 4 ---------------------------------------------------------
lay<- as.matrix(cbind(c(1,1,2), c(3,3,4)))
setwd(DIR_out); pdf("000_Figure_4.pdf", width = 6, height = 6)
grid::grid.draw(grid.arrange(p1,p2,p3,p4, layout_matrix =lay))
dev.off()

setwd(DIR_out); png("000_Figure_4.png", width = 6, height =6, units = "in",res = 300)
grid.arrange(p1,p2,p3,p4, layout_matrix =lay)
dev.off()


# model for table S6 -----------------------------------------------------------
zaaa$treat <- "EH0_80"
zzzz$treat <- "EH20_60"
znnn$treat <- "EH0_40"
zppp$treat <- "EH40_80"
tempdata <- rbind(zaaa, zzzz, znnn, zppp)
tempdata$cost <- tempdata$dist*tempdata$sign
tempdata$treat <- factor(tempdata$treat, levels = c("EH0_40", "EH20_60", "EH0_80", "EH40_80"))
# hist(tempdata$cost)
mymod <- lm(cost ~ treat + 0, data = tempdata)
summary(mymod)
setwd(DIR_out); print(tab_model(mymod, digits=5, digits.p=8, show.stat=T, wrap.labels=100,
                      file=paste0("000_Table_S6.html")))
rm(mymod)

# significant individuals ------------------------------------------------------
print("total")
table(tempdata$treat)
print("n with cost")
table(tempdata[tempdata$cost <= -0.0216,]$treat)
print("p with cost")
table(tempdata[tempdata$cost <= -0.0216,]$treat)/table(tempdata$treat)
print("n neutral")
table(tempdata[tempdata$cost > -0.0216 & tempdata$cost < 0.0216,]$treat)
print("p neutral")
table(tempdata[tempdata$cost > -0.0216 & tempdata$cost < 0.0216,]$treat)/table(tempdata$treat)
print("n with benefit")
table(tempdata[tempdata$cost >= 0.0216,]$treat)  
print("p with benefit")
table(tempdata[tempdata$cost >= 0.0216,]$treat)/table(tempdata$treat)

rm(tempdata, aaa, zaaa, nnn, znnn, ppp, zppp, qqq, zqqq, zzz, zzzz,
   p1, p2, p3, p4, lay, legp)
```
<br/><br/>


```{R Costs of Generalization 0,40: legend, warning = FALSE}
m <- myrcw[myrcw$treat %in% c("EH0_40", "EH0_80"),]
legp <- ggplot(data = m, aes( x = dw_00, y = dw_80, color = treat))+
  geom_point(size = 2) + theme_VJF() + scale_color_manual(values = mypalette[c(2,5)]) + labs(color = "Treatment") + guides(color = guide_legend(reverse = T))+
  theme(legend.title = element_text(size = 8), 
          legend.text = element_text(size = 8))
legp <- get_legend(legp)
rm(m)
```
<br/><br/>


```{R Costs of Generalization 0,40: Figure panels A and C, warning = FALSE}
# get values -------------------------------------------------------------------
m <- myrcw[myrcw$treat == "EH0" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80) & !is.na(myrcw$dw_00_40),]
EH0in00 <- mean(m$dw_00, na.rm = T)
EH0in40 <- mean(m$dw_40, na.rm = T)
EH0in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_40),]
EH40in00 <- mean(m$dw_00, na.rm = T)
EH40in40 <- mean(m$dw_40, na.rm = T)
EH40in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH80" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH80in00 <- mean(m$dw_00, na.rm = T)
EH80in40 <- mean(m$dw_40, na.rm = T)
EH80in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_80),]
EH0_80in00 <- mean(m$dw_00, na.rm = T)
EH0_80in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("SALT_A", "SALT_B") & !is.na(myrcw$dw_00_40),]
EH0_40in00 <- mean(m$dw_00, na.rm = T)
EH0_40in40 <- mean(m$dw_40, na.rm = T)
EH0_40in80 <- mean(m$dw_80, na.rm = T); rm(m)


# Panel B ----------------------------------------------------------------------
a <- c(EH0_80in00, EH0_80in80)
b <- c(EH0in00, EH0in80)
c <- c(EH80in00, EH80in80)

mmm <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_80")]
mmm <- mmm[!is.na(mmm$dw_00) & !is.na(mmm$dw_80),]
mmm$dist <- apply(cbind(mmm$dw_00, mmm$dw_80), 1, dist2d, b=b, c=c)
mmm$sign <- apply(cbind(mmm$dw_00, mmm$dw_80), 1, lineside, b=b, c=c)

getline(b, c) # line (slope, intercept)
dist2d(a, b, c) # distance to line for generalist
nrow(mmm[mmm$sign < 0,])/nrow(mmm) # prop on side 1
nrow(mmm[mmm$sign > 0,])/nrow(mmm) # prop on side 2

p1 <- ggplot(data = mmm, aes(x = dw_00, y = dw_80))+ geom_rug(data=mmm, aes(x = dw_00, y = dw_80), color = mypalette[5])+
  xlim(min(b[1], c[1], mmm$dw_00)*1.10,max(b[1], c[1], mmm$dw_00)*1.10) + ylim(min(b[2], c[2], mmm$dw_80)*1.10,max(b[2], c[2], mmm$dw_80)*1.10)+
  geom_abline(slope = getline(b, c)[1], intercept = getline(b, c)[2], lty = "dotdash") +
  geom_point(pch = 1, color = mypalette[5], size = 0.75)+
  geom_point(x=a[1], y=a[2], fill = mypalette[5], size = 3, pch = 21)+
  geom_point(x=b[1], y=b[2], color = "black", size = 2)+
  geom_point(x=c[1], y=c[2], color = "black", size = 2)+
  theme_VJF()+ xlab("Fitness Change (%) in 0% NaCl")+ylab("Fitness Change (%) in 80% NaCl")+ labs(tag="B")

# Panel A ----------------------------------------------------------------------
a <- c(EH0_40in00, EH0_40in40)
b <- c(EH0in00, EH0in40)
c <- c(EH40in00, EH40in40)
nnn <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("SALT_A", "SALT_B"), c("dw_00", "dw_40")]
nnn <- nnn[!is.na(nnn$dw_00) & !is.na(nnn$dw_40),]
nnn$dist <- apply(cbind(nnn$dw_00, nnn$dw_40), 1, dist2d, b=b, c=c)
nnn$sign <- apply(cbind(nnn$dw_00, nnn$dw_40), 1, lineside, b=b, c=c)

getline(b, c) # line (slope, intercept)
dist2d(a, b, c) # distance to line for generalist
nrow(nnn[nnn$sign < 0,])/nrow(nnn) # prop on side 1
nrow(nnn[nnn$sign > 0,])/nrow(nnn) # prop on side 2

p2 <- ggplot(data = nnn, aes(x = dw_00, y = dw_40))+ geom_rug(data=nnn, aes(dw_00, y = dw_40), color = mypalette[2])+
  xlim(min(b[1], c[1], nnn$dw_00)*1.10,max(b[1], c[1], nnn$dw_00)*1.10) + ylim(min(b[2], c[2], nnn$dw_40)*1.10,max(b[2], c[2], nnn$dw_40)*1.10)+
  geom_abline(slope = getline(b, c)[1], intercept = getline(b, c)[2], lty = "dotdash") +
  geom_point(pch = 1, color = mypalette[2], size = 0.75)+
  geom_point(x=a[1], y=a[2], fill = mypalette[2], size = 3, pch = 21)+
  geom_point(x=b[1], y=b[2], color = "black", size = 2)+
  geom_point(x=c[1], y=c[2], color = "black", size = 2)+
  theme_VJF()+ xlab("Fitness Change (%) in 0% NaCl")+ylab("Fitness Change (%) in 40% NaCl")+ labs(tag="A")

# Panel C ----------------------------------------------------------------------
p4 <- ggplot()+
  geom_vline(aes(xintercept = 0), color = "black", lty = "dotdash")+
  geom_vline(aes(xintercept = mean(mmm$dist*mmm$sign)), lty = "dotted", color = mypalette[5])+
  geom_vline(aes(xintercept = mean(nnn$dist*nnn$sign)), lty = "dotted", color = mypalette[2])+
  geom_density(data = mmm, aes(x = dist*sign), color = mypalette[5]) + geom_rug(data=mmm, aes(x=dist*sign), color = mypalette[5])+
  geom_density(data = nnn, aes(x = dist*sign), color = mypalette[2]) + geom_rug(data=nnn, aes(x=dist*sign), color = mypalette[2])+
  theme_VJF() + annotation_custom(legp, xmin = 0.025, ymin = 10)+
  xlab("Cost") + ylab("Density")+ labs(tag="C")

rm(EH0_40in00, EH0_40in40, EH0_40in80,
   EH0_80in00, EH0_80in80,
   EH0in00, EH0in40, EH0in80,
   EH40in00, EH40in40, EH40in80,
   EH80in00, EH80in40, EH80in80) # tidy
```
<br/><br/>


```{R Costs of Generalization 0,40: Figure panels B and D, warning = FALSE}
# get values -------------------------------------------------------------------
m <- myrcw[myrcw$treat == "EH0" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80) & !is.na(myrcw$dw_00_40),]
EH0in00 <- mean(m$dw_00, na.rm = T)
EH0in40 <- mean(m$dw_40, na.rm = T)
EH0in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH40" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_40),]
EH40in00 <- mean(m$dw_00, na.rm = T)
EH40in40 <- mean(m$dw_40, na.rm = T)
EH40in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH80" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH80in00 <- mean(m$dw_00, na.rm = T)
EH80in40 <- mean(m$dw_40, na.rm = T)
EH80in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_80),]
EH0_80in00 <- mean(m$dw_00, na.rm = T)
EH0_80in80 <- mean(m$dw_80, na.rm = T); rm(m)

m <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("COPR_A", "COPR_B") & !is.na(myrcw$dw_00_40),]
EH0_40in00 <- mean(m$dw_00, na.rm = T)
EH0_40in40 <- mean(m$dw_40, na.rm = T)
EH0_40in80 <- mean(m$dw_80, na.rm = T); rm(m)


# Panel E ----------------------------------------------------------------------
a <- c(EH0_80in00, EH0_80in80)
b <- c(EH0in00, EH0in80)
c <- c(EH80in00, EH80in80)
zmmm <- myrcw[myrcw$treat == "EH0_80" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_80")]
zmmm <- zmmm[!is.na(zmmm$dw_00) & !is.na(zmmm$dw_80),]
zmmm$dist <- apply(cbind(zmmm$dw_00, zmmm$dw_80), 1, dist2d, b=b, c=c)
zmmm$sign <- apply(cbind(zmmm$dw_00, zmmm$dw_80), 1, lineside, b=b, c=c)

getline(b, c) # line (slope, intercept)
dist2d(a, b, c) # distance to line for generalist
nrow(zmmm[zmmm$sign < 0,])/nrow(zmmm) # prop on side 1
nrow(zmmm[zmmm$sign > 0,])/nrow(zmmm) # prop on side 2

zp1 <- ggplot(data = zmmm, aes(x = dw_00, y = dw_80))+ geom_rug(data=zmmm, aes(x = dw_00, y = dw_80), color = mypalette[5])+
  xlim(min(b[1], c[1], zmmm$dw_00)*1.10,max(b[1], c[1], zmmm$dw_00)*1.10) + ylim(min(b[2], c[2], zmmm$dw_80)*1.10,max(b[2], c[2], zmmm$dw_80)*1.10)+
  geom_abline(slope = getline(b, c)[1], intercept = getline(b, c)[2], lty = "dotdash") +
  geom_point(pch = 1, color = mypalette[5], size = 0.75)+
  geom_point(x=a[1], y=a[2], fill = mypalette[5], size = 3, pch = 21)+
  geom_point(x=b[1], y=b[2], color = "black", size = 2)+
  geom_point(x=c[1], y=c[2], color = "black", size = 2)+
  theme_VJF()+ xlab(expression(bold("Fitness Change (%) in 0% "*CuSO["4"]*"")))+ylab(expression(bold("Fitness Change (%) in 80% "*CuSO["4"]*"")))+ labs(tag="E")

# Panel D ----------------------------------------------------------------------
a <- c(EH0_40in00, EH0_40in40)
b <- c(EH0in00, EH0in40)
c <- c(EH40in00, EH40in40)
znnn <- myrcw[myrcw$treat == "EH0_40" & myrcw$epo %in% c("COPR_A", "COPR_B"), c("dw_00", "dw_40")]
znnn <- znnn[!is.na(znnn$dw_00) & !is.na(znnn$dw_40),]
znnn$dist <- apply(cbind(znnn$dw_00, znnn$dw_40), 1, dist2d, b=b, c=c)
znnn$sign <- apply(cbind(znnn$dw_00, znnn$dw_40), 1, lineside, b=b, c=c)

getline(b, c) # line (slope, intercept)
dist2d(a, b, c) # distance to line for generalist
nrow(znnn[znnn$sign < 0,])/nrow(znnn) # prop on side 1
nrow(znnn[znnn$sign > 0,])/nrow(znnn) # prop on side 2

zp2 <- ggplot(data = znnn, aes(x = dw_00, y = dw_40))+ geom_rug(data=znnn, aes(dw_00, y = dw_40), color = mypalette[2])+
  xlim(min(b[1], c[1], znnn$dw_00)*1.10,max(b[1], c[1], znnn$dw_00)*1.10) + ylim(min(b[2], c[2], znnn$dw_40)*1.10,max(b[2], c[2], znnn$dw_40)*1.10)+
  geom_abline(slope = getline(b, c)[1], intercept = getline(b, c)[2], lty = "dotdash") +
  geom_point(pch = 1, color = mypalette[2], size = 0.75)+
  geom_point(x=a[1], y=a[2], fill = mypalette[2], size = 3, pch = 21)+
  geom_point(x=b[1], y=b[2], color = "black", size = 2)+
  geom_point(x=c[1], y=c[2], color = "black", size = 2)+
  theme_VJF()+ xlab(expression(bold("Fitness Change (%) in 0% "*CuSO["4"]*"")))+ylab(expression(bold("Fitness Change (%) in 40% "*CuSO["4"]*"")))+ labs(tag="D")

# Panel F ----------------------------------------------------------------------
zp4 <- ggplot()+
  geom_vline(aes(xintercept = 0), color = "black", lty = "dotdash")+
  geom_vline(aes(xintercept = mean(zmmm$dist*zmmm$sign)), lty = "dotted", color = mypalette[5])+
  geom_vline(aes(xintercept = mean(znnn$dist*znnn$sign)), lty = "dotted", color = mypalette[2])+
  geom_density(data = zmmm, aes(x = dist*sign), color = mypalette[5]) + geom_rug(data=zmmm, aes(x=dist*sign), color = mypalette[5])+
  geom_density(data = znnn, aes(x = dist*sign), color = mypalette[2]) + geom_rug(data=znnn, aes(x=dist*sign), color = mypalette[2])+
  theme_VJF()+ xlab("Cost") + ylab("Density")+ labs(tag="F")

# full figure ------------------------------------------------------------------
setwd(DIR_out); pdf("000_Figure_S3.pdf", width = 11/1.25, height =8.5/1.25)
grid.arrange(p2,p1,p4,zp2,zp1,zp4, ncol = 3)
dev.off()

setwd(DIR_out); png("000_Figure_S3.png", width = 11/1.25, height =8.5/1.25, units = "in",res = 300)
grid.arrange(p2,p1,p4,zp2,zp1,zp4, ncol = 3)
dev.off()

rm(EH0_40in00, EH0_40in40, EH0_40in80,
   EH0_80in00, EH0_80in80,
   EH0in00, EH0in40, EH0in80,
   EH40in00, EH40in40, EH40in80,
   EH80in00, EH80in40, EH80in80,
   a,b,c, legp, mmm, nnn, p1, p2, p4, zmmm, znnn,
   zp1, zp2, zp4) # tidy
```
<br/><br/>

